import Head from 'next/head'
import { useState } from 'react'
// import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import NavList from '../components/NavList'
import request from '../utils/http'
import NoData from '../components/NoData'
async function getData(id = '') {
  console.log(id)
  try {
    const {
      data: {
        data: { data }
      }
    } = await request({
      url: '/blogs/getBlogs',
      method: 'get',
      data: {
        tagId: id,
        currentPage: 1,
        pageSize: 20
      }
    })
    return data || []
  } catch (e) {
    console.log(e)
  }
}

export async function getServerSideProps() {
  const {
    data: { data }
  } = await request({
    url: '/tags/getTags',
    method: 'get'
  })
  // console.log(data, 'data')
  if (data && data.length) {
    const res = await getData()
    // console.log(res, 'res')
    return {
      props: {
        blogList: res,
        navList: data
      }
    }
  } else {
    return {
      props: {
        blogList: [],
        navList: []
      }
    }
  }
}
export default function Home(props) {
  const blogList = JSON.parse(JSON.stringify(props.blogList))
  const [list, setList] = useState(blogList)
  const itemClick = async (id) => {
    const res = await getData(id)
    setList(res)
  }
  function createMarkup(content) {
    return { __html: content }
  }
  return (
    <>
      <Head>
        <title>首页-weng的博客</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <main className={styles.main}>
        <NavList data={props.navList} itemClick={itemClick}></NavList>
        <div className={styles.content}>
          <ul>
            {list.length ? (
              list.map((item) => {
                return (
                  <Link href={'/details/' + item._id} key={item._id} passHref>
                    <li className={styles.liItem}>
                      <h2 className={styles.blogTitle}>{item.title}</h2>
                      <div className="es" dangerouslySetInnerHTML={createMarkup(item.content)}></div>
                    </li>
                  </Link>
                )
              })
            ) : (
              <NoData />
            )}
          </ul>
        </div>
      </main>
    </>
  )
}
